### ISSUE TITLE
Too many element types registered

### ISSUE THREAD

**Issue by rillig** [thefallentree/idea-bison#1]
I tried out your Bison plugin. Thank you for creating it, so that I don't have to use the goyacc plugin for C-style grammars anymore.

When I installed the plugin, CLion complained:

> java.lang.Throwable: Too many element types registered. Out of (short) range. Most of element types (11433) were registered for 'Language: Bison':
>
> ALIAS, BRACED_CODE, CODE_PROPS_TYPE, EPILOGUE, GENERIC_SYMLIST_ITEM, GRAMMAR_DECLARATION, ID_OR_CHAR_LITERAL, NTERM_DECLS, PRECEDENCE_DECLARATOR, PREDICATE, PROLOGUE, PROLOGUE_DECLARATION, RHS, RULES, RULES_OR_GRAMMAR_DECLARATION, STRING_AS_ID, SYMBOL, SYMBOL_DECLARATION, TAG, TOKEN_DECL, TOKEN_DECL...

The token types from that list all look sensible to me, so I wonder why [CLion thinks there are 11433 of them](https://github.com/JetBrains/intellij-community/blob/94f3e9b31406ba3b72e913666623c75a665b22b6/platform/core-api/src/com/intellij/psi/tree/IElementType.java#L115). Do you have any idea?

**Comment by thefallentree** [comment]
Have you updated to latest version? That has been fixed.

**Comment by rillig** [comment]
https://plugins.jetbrains.com/plugin/16595-bison-language-support/versions says the latest version is from 2021-05-01, and I'm using that.

Interestingly, the number of tokens increases when I continue to edit a Bison file, so it looks to me as if the token types were registered more often than necessary.

**Comment by thefallentree** [comment]
Yeah, https://github.com/thefallentree/idea-bison/commit/32cc007f045e8339b8073f535bbd1321f4d7cd05#diff-bb53ce76f14ae2598d57a459b909d2632d0191b698d598092a2b09ea79d66767R24 was suppose to fix it ( look at  BisonTokenType.directive()) 

so maybe something is still missing.

**Comment by rillig** [comment]
I can reproduce the bug by repeatedly pressing Space and Backspace anywhere in a Bison editor, about 10 times.

Each time the exception is thrown the number of registered tokens raises by about 20.

**Comment by thefallentree** [comment]
Ok, I will take a look later tonight … can you count how many directive you
have?  Those %commands

**Comment by rillig** [comment]
The file in question is [this grammar](https://github.com/NetBSD/src/blob/trunk/usr.bin/xlint/lint1/cgram.y), which has between 150 and 200 `%` commands.

**Comment by thefallentree** [comment]
issue is fixed in ebe8bd46fffc07dcd555f46a0bebc6ea2f575a67 ,  new version is published once approved you should be able to update!

Cheers.

**Comment by rillig** [comment]
Thank you for fixing the plugin so quickly. JetBrains have approved the update, and it works like a charm now.

**Comment by thefallentree** [comment]
No problem, enjoy!
