### ISSUE TITLE
[feature] Add structure overview

### ISSUE THREAD

**Issue by rillig** [thefallentree/idea-bison#2]
Hi, Just in case you want to spend some more time on this plugin: There is a feature from the [GoYacc plugin](https://plugins.jetbrains.com/plugin/11444-goyacc-support) that I'm missing in the Bison plugin, and that is to have a structural overview over the grammar.

The [implementation in the GoYacc plugin](https://github.com/zyguan/idea-goyacc/blob/9decc6a6af291766bc4b1949a2f95714221a8b47/src/main/scala/idea/goyacc/insight/GoYaccStructureViewFactory.scala#L17) looks reasonably short, and there is [documentation for writing a StructureViewFactory](https://plugins.jetbrains.com/docs/intellij/structure-view-factory.html), so it looks doable.

This would allow to see the grammar rules by pressing Ctrl+F12, and also to quickly jump to a particular grammar rule.

**Comment by thefallentree** [comment]
Done!
