### ISSUE TITLE
Huge Grammer file is not parsed correctly

### ISSUE THREAD

**Issue by konsultaner** [thefallentree/idea-bison#3]
I'm currently contributing to https://github.com/arangodb/arangodb but for some reason their [grammer.y](https://github.com/arangodb/arangodb/blob/38fdb5293a833de42ddb611df4b1859128704e32/arangod/Aql/grammar.y) file does not work with your plugin correctly. Is it wrongly formatted?

**Comment by thefallentree** [comment]
#4 should fix this
