### ISSUE TITLE
'%%' or <rules or grammar declaration> expected, got '|'

### ISSUE THREAD

**Issue by francisdb** [thefallentree/idea-bison#8]
Got the following error when opening https://github.com/wine-mirror/wine/blob/master/dlls/vbscript/parser.y

```
'%%' or <rules or grammar declaration> expected, got '|'
```

![image](https://github.com/thefallentree/idea-bison/assets/161305/f7a20f3b-2e60-42cf-8e6c-3fd60bc2d7ad)

**Comment by sigmasternchen** [comment]
There is an error in the grammar. The semicolon at the end of the third line in the screenshot is probably wrong.

**Comment by francisdb** [comment]
Thanks, proposed a fix on the other side.
https://github.com/wine-mirror/wine/pull/38
